# Generated by Django 4.0.5 on 2022-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mebelforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mebelforma',
            name='Manzil',
            field=models.CharField(max_length=100),
        ),
    ]
